name: Trigger Documentation Sync

on:
  push:
    branches:
      - main

jobs:
  trigger-doc-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger sync_docs in documentation repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/yangyu-1997/my-vitepress-site/dispatches \
          -d '{"event_type": "sync_docs"}'
